---
title: "Time Series Forecasting"
subtitle: "Chapter 3"
author: "Pramod Duvvuri"
date: "4/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=5)
```

## Simple Forecasting Methods

```{r}
## Loading Packages
library("pacman")
p_load("fpp2")
```

```{r}
## Average Method
y <- ts(c(123, 39, 78, 52, 110), start = 2012)
h <- 1
meanf(y, h)
```

```{r echo=TRUE}
## Usage of knitr for Rmd Tables
p_load("knitr")
kable(meanf(y, h))
```

```{r}
## Naive Method
naive(y, h)
rwf(y, h) # Equivalent alternative
```

```{r}
## Seasonal Naive
snaive(y, h)
```

```{r}
## Drift Method
rwf(y, h, drift = TRUE)
```

```{r}
# Set training data from 1992 to 2007
beer2 <- window(ausbeer, start = 1992, end = c(2007, 4))
# Plot some forecasts
autoplot(beer2) +
  autolayer(meanf(beer2, h = 11),
            series = "Mean", PI = FALSE) +
  autolayer(naive(beer2, h = 11),
            series = "Na誰ve", PI = FALSE) +
  autolayer(snaive(beer2, h = 11),
            series = "Seasonal na誰ve", PI = FALSE) +
  ggtitle("Forecasts for quarterly beer production") +
  xlab("Year") + ylab("Megalitres") +
  guides(colour = guide_legend(title = "Forecast"))
```

```{r}
autoplot(goog200) +
  autolayer(meanf(goog200, h = 40),
            series = "Mean", PI = FALSE) +
  autolayer(rwf(goog200, h = 40),
            series = "Na誰ve", PI = FALSE) +
  autolayer(rwf(goog200, drift = TRUE, h = 40),
            series = "Drift",
            PI = FALSE) +
  ggtitle("Google stock (daily ending 6 Dec 2013)") +
  xlab("Day") + ylab("Closing Price (US$)") +
  guides(colour = guide_legend(title = "Forecast"))
```

## Transformations and Adjustments

### Calendar Adjustment

```{r}
dframe <- cbind(Monthly = milk,
                DailyAverage = milk/monthdays(milk))
  autoplot(dframe, facet=TRUE) +
    xlab("Years") + ylab("Pounds") +
    ggtitle("Milk production per cow")
```

### Mathematical Adjustments (Box-Cox Transformations)

```{r}
(lambda <- BoxCox.lambda(elec))
autoplot(BoxCox(elec,lambda))
```

### Bias Adjustments

```{r}
fc <- rwf(eggs, drift=TRUE, lambda=0, h=50, level=80)
fc2 <- rwf(eggs, drift=TRUE, lambda=0, h=50, level=80,
  biasadj=TRUE)
autoplot(eggs) +
  autolayer(fc, series="Simple back transformation") +
  autolayer(fc2, series="Bias adjusted", PI=FALSE) +
  guides(colour=guide_legend(title="Forecast"))
```

## Residual Analysis

```{r}
autoplot(goog200) +
  xlab("Day") + ylab("Closing Price (US$)") +
  ggtitle("Google Stock (daily ending 6 December 2013)")
```

```{r}
res <- residuals(naive(goog200))
autoplot(res) + xlab("Day") + ylab("") +
  ggtitle("Residuals from na誰ve method")
```

```{r}
gghistogram(res) + ggtitle("Histogram of residuals")
```

```{r}
ggAcf(res) + ggtitle("ACF of residuals")
```

### Portmanteau Tests for Autocorrelation

```{r}
Box.test(res, lag=10, fitdf=0)
Box.test(res,lag=10, fitdf=0, type="Lj")
```

```{r}
checkresiduals(naive(goog200))
```

